---
- hosts: debian12
  become: yes
  tasks:
    - name: Install fingerprint components
      apt:
        name:
          - fprintd
          - libfprint-2-2
          - libpam-fprintd
        state: present

    # NOT TESTES - may have serious consequences. Have a backup!
    - name: Add pam_fprintd.so to /etc/pam.d/common-auth
      lineinfile:
        path: /etc/pam.d/common-auth
        line: 'auth sufficient /lib/x86_64-linux-gnu/security/pam_fprintd.so'
        insertbefore: BOF
