---
- hosts: localhost
  become: yes
  tasks:
    - name: Uninstall games
      apt:
        name:
          - gnome-games
          - gnome-games-data
          - gnome-games-extra-data
          - bsdgames
        state: absent
