---
- hosts: localhost
  become: yes
  tasks:
    - name: Install Wireguard
      apt:
        name: wireguard
        state: present

    - name: Enable Wireguard at startup
      systemd:
        name: wg-quick@franz.t440s
        enabled: yes
